[package]
name = "esg"
version = "0.1.0"
description = "ESG - Gestor de programas para Linux"
authors = ["raux"]
edition = "2021"

[lib]
name = "esg_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["process", "io-util", "sync", "time", "macros", "rt-multi-thread"] }
portable-pty = "0.9"
regex = "1"

[profile.release]
strip = true
lto = true
codegen-units = 1
